### ISSUE TITLE
Button OK in gMailOOo Message Box not works

### ISSUE THREAD

**Issue by fabriziobogli** [prrvchr/gMailOOo#1]
Hi, 
I have a little issue: I obtain the authorization code, I can
"copy and paste authorization code to LibreOffice gMailOOo Message Box"
but when I press "OK" nothing happens.
Tried both 0.0.1 and 0.0.2 versions.
Libre Office 5.3.4.2
Windows 10 Pro

Thanks
Fabrizio Bogli

**Comment by prrvchr** [comment]
Hi fabriziobogli,

> I obtain the authorization code, I can "copy and paste authorization code to LibreOffice gMailOOo Message Box" but when I press "OK" nothing happens.

The authorization code is used to retrieve the tokens, via JSON and an HTTP request: can be a firewall problem ... Try again with firewall disabled...

**Comment by fabriziobogli** [comment]
Hi,
thanks for your answer.
I have no firewall and I DO obtain from Gmail the correct authorization
code (a long alphanumeric string).
I copy it to  LibreOffice gMailOOo Message Box.
When I press "OK" the code remains in the message box and nothing else
happens, even I press repeately the button.
Wishing you can help me.
Thank you
Fabrizio Bogli

2017-07-12 8:41 GMT+02:00 prrvchr <notifications@github.com>:

**Comment by prrvchr** [comment]
Hi,

I can not test under windows 10, only windows 7, due to lack of time and computer available...

I will try to do these tests, when I finished the rewrite of gContactOOo (Google Contact OOo integration)

**Comment by fabriziobogli** [comment]
Thank you very much
I'll wait for this
Hi,
Fabrizio Bogli

2017-07-12 15:05 GMT+02:00 prrvchr <notifications@github.com>:

**Comment by prrvchr** [comment]
Ok, I close this issue when this is done... :-)

**Comment by prrvchr** [comment]
Hi Fabrizio,

Requests as been embedded in version 0.0.4.
Can you confirm that this version works?

Thank
