### ISSUE TITLE
how i send email from libreoffice

### ISSUE THREAD

**Issue by ljrossi** [prrvchr/gMailOOo#2]
HI

Ok, I look that the extension has correctly been setup on Libreoffice V: 5.2.7.2 ,on linux Debian 9, i added the key code given by gmail.

But when i go to "menu-files-send by email" , i still get the option to send it by "Evolution"....
Maybe this a libreoffice question, but how or where I have to go to actually send the document by gmailOOo.

I whent to the macros, and there it seems to bee, all the 3 folder are there _license , Mailservice , MailMessage , I try a bunch of macro in there, but all with error "Missing parameters" ....

Regards

**Comment by prrvchr** [comment]
Hi ljrossi,

> But when i go to "menu-files-send by email" , i still get the option to send it by "Evolution"....

It's normal, this option uses your email client to send an email.

You can try Menu: Tools -> Mail Merge Wizard, but you must setup: Tools -> Address Book Source, before...
I am writing an extension that will send mail and merge with the Google Contact address book.
It is not yet available but soon.

**Comment by prrvchr** [comment]
With gMailOOo your Google Mail password is no longer stored in LibreOffice

 To send mail you have to use gContactOOo.
